@startuml

package Controller {
    class LoginController {
      - emailField : TextField
      - passwordField : PasswordField
      - img : ImageView
      + onLoginButtonClick() : void
      + onRegisterButtonClick() : void
      + onCodeLoginButtonClick() : void
    }

    class RegisterController {
      - emailField : TextField
      - confirmEmailField : TextField
      - passwordField : PasswordField
      - confirmPasswordField : PasswordField
      - emailErrorLabel : Label
      - confirmEmailErrorLabel : Label
      - passwordErrorLabel : Label
      - confirmPasswordErrorLabel : Label
      - emailValidLabel : Label
      - passwordValidLabel : Label
      + initialize() : void
      + slideToLogin() : void
      + validatePassword() : void
      + validatePasswordMatch() : void
      + validateEmail() : void
      + validateEmailMatch() : void
      + playFadeTransition(label : Label) : void
    }

}

@enduml